### PR TITLE
Customizable paths for Role

### PR DESCRIPTION
**Pull request by ProstoNikita**
Added gitea_user_home, gitea_executable_path and gitea_configuration_path for gitea role
 
 Can you update README?

### CODE REVIEW

**Comment by ProstoNikita** [comment]
This PR fixes #86

**Review by DO1JLR — APPROVED** [review]

**Comment by DO1JLR** [comment]
thanks a lot :heart:

**Comment by ProstoNikita** [comment]
@DO1JLR I think README doesn't have description of this variables, can you add it? :)

**Comment by DO1JLR** [comment]
Sure, will do that.

**Pull request merged**
